// Blocklist of known disposable/temporary email domains
export const DISPOSABLE_EMAIL_DOMAINS = new Set([
  // Major disposable email services
  "tempmail.com", "temp-mail.org", "temp-mail.io", "tempmailo.com",
  "guerrillamail.com", "guerrillamail.net", "guerrillamail.org", "guerrillamail.de",
  "guerrillamailblock.com", "grr.la", "sharklasers.com", "guerrilla.ml",
  "10minutemail.com", "10minutemail.net", "10minutemail.org", "10minute.email",
  "yopmail.com", "yopmail.fr", "yopmail.net", "yopmail.gq",
  "mailinator.com", "mailinator.net", "mailinator2.com", "maildrop.cc",
  "throwaway.email", "throwawaymail.com", "throwawaymailme.com",
  "dispostable.com", "disposableemailaddresses.emailmiser.com",
  "trashmail.com", "trashmail.me", "trashmail.net", "trashmail.org",
  "fakeinbox.com", "fakemail.fr", "fakemail.net",
  "mailnesia.com", "mailnator.com", "mailcatch.com",
  "tempinbox.com", "tempr.email", "tempmailaddress.com",
  "emailondeck.com", "emailfake.com",
  "getnada.com", "nada.email", "nada.ltd",
  "mohmal.com", "mohmal.in", "mohmal.im",
  "mailtemp.org", "mailtemp.net",
  "harakirimail.com", "harakirimail2.com",
  "safetymail.info", "safetypost.de",
  "spambox.us", "spamfree24.org", "spamgourmet.com",
  "mytemp.email", "mytempmail.com",
  "emailtmp.com", "tmpmail.org", "tmpmail.net",
  "crazymailing.com", "deadfake.cf",
  "discard.email", "discardmail.com", "discardmail.de",
  "emkei.cz", "fiveavetempmail.com",
  "getairmail.com", "guerrillamail.info",
  "inboxalias.com", "jetable.org",
  "kasmail.com", "koszmail.pl",
  "mailforspam.com", "mailhazard.com",
  "mailhazard.us", "mailhub.pro",
  "mailnull.com", "mailscrap.com",
  "mailshell.com", "mailzilla.com",
  "nomail.xl.cx", "nowmymail.com",
  "objectmail.com", "ownmail.net",
  "proxymail.eu", "rcpt.at",
  "reallymymail.com", "recode.me",
  "regbypass.com", "s0ny.net",
  "skeefmail.com", "sogetthis.com",
  "spamcero.com", "spamex.com",
  "spamfree.eu", "spammotel.com",
  "tempemail.biz", "tempemail.co.za",
  "tempemail.com", "tempemail.net",
  "tempsky.com", "thankyou2010.com",
  "trashemail.de", "trashymail.com",
  "trashymail.net", "turual.com",
  "twinmail.de", "uggsrock.com",
  "upliftnow.com", "venompen.com",
  "veryrealemail.com", "viditag.com",
  "viewcastmedia.com", "viewcastmedia.net",
  "wegwerfmail.de", "wegwerfmail.net",
  "wetrainbayarea.com", "wetrainbayarea.org",
  "wh4f.org", "whyspam.me",
  "wickmail.net", "wilemail.com",
  "willselfdestruct.com", "winemaven.info",
  "wronghead.com", "wuzup.net",
  "wuzupmail.net", "wwwnew.eu",
  "xagloo.com", "xemaps.com",
  "xents.com", "xjoi.com",
  "xyzfree.net", "yogamaven.com",
  "yomail.info", "yuurok.com",
  "zehnminutenmail.de", "zippymail.info",
  "zoaxe.com", "zoemail.org",
  // Additional common ones
  "mintemail.com", "flitafir.de", "lackmail.net",
  "emailna.co", "emailna.life", "burnermail.io",
  "guerrillamail.biz", "grr.la", "emailgo.de",
]);

export function isDisposableEmail(email: string): boolean {
  const domain = email.split("@")[1]?.toLowerCase();
  if (!domain) return false;
  return DISPOSABLE_EMAIL_DOMAINS.has(domain);
}
